// This service handles the generation of "Peace of Mind" reports for parents.
// In a real implementation, this would use `react-pdf` or a server-side library like `puppeteer`.

export type ParentReportData = {
  studentName: string;
  careerTitle: string;
  totalCost: number;
  expectedSalary: number;
  breakEvenYears: number;
  safetyScore: number;
  aiResistanceScore: number; // 1-10
};

export async function generateParentReport(data: ParentReportData) {
  // Logic to generate PDF buffer would go here.
  // For now, we return a structured HTML string that could be printed.
  
  const html = `
    <html>
      <body>
        <h1>Career Viability Report for ${data.studentName}</h1>
        <h2>Target Career: ${data.careerTitle}</h2>
        <hr />
        
        <h3>Financial Analysis</h3>
        <p><strong>Total Investment:</strong> ₹${data.totalCost.toLocaleString()}</p>
        <p><strong>Starting Salary:</strong> ₹${data.expectedSalary.toLocaleString()}</p>
        <p><strong>ROI Break-even:</strong> ${data.breakEvenYears} Years</p>

        <h3>Peace of Mind Metrics</h3>
        <p><strong>Campus Safety Score:</strong> ${data.safetyScore}/10</p>
        <p><strong>Future Proof (AI Resistance):</strong> ${data.aiResistanceScore}/10</p>

        <p><em>Generated by Next Career India</em></p>
      </body>
    </html>
  `;

  return html;
}
